### ISSUE TITLE
Labels don't get removed

### ISSUE THREAD

**Issue by mukherjeer-mms** [rogerluan/label-remover#391]
Hi, I am using this action but it is not removing the labels and throwing an ```HttpError: Not Found```. I am suspecting that the action is treating other environment variable as a label and trying to remove it, and throwing an error because it does not exist as a label in the PR.  Would you please be able to shade some light?

Here is my step: 

```
- name: remove label
        if: contains(steps.pr-labels.outputs.labels, 'deployed-feature') 
        # remove all 'deployed' labels when adding more commits in the PR
        uses: rogerluan/label-remover@v1.0.1
        with:
          github_token	: ${{ secrets.PUSH_TOKEN_FOR_GITHUB }}
```

And here is the output

```
Run rogerluan/label-remover@v1.0.1
  with:
    github_token: ***
  env:
    GITHUB_PR_LABEL_DEPLOY_ME: 1
    GITHUB_PR_LABEL_DO_NOT_MERGE: 1
    GITHUB_PR_LABEL_BUILD_APP: 1
    GITHUB_PR_LABEL_DEPLOYED_FEATURE: 1
    PR_LABELS:  deploy-me do-not-merge build-app deployed-feature 
Error: HttpError: Not Found
Error: Not Found
``` 

Many thanks in advance!

Edit: My assumption was wrong, the action did not work even after removing other env variable.
